source_stream_name = "stg_shot_events"
output_stream_name = "stg_shot_predictions"
model_bucket = "stg-mlflow-models-shot-xgoals"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stg_stream_model_xgoals"
lambda_function_name = "stg_prediction_lambda"
