services:
  backend:
    environment:
    - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
    - RUN_ID=${RUN_ID}
    - AWS_DEFAULT_REGION=us-east-1
    - MODEL_LOCATION=/app/model
    - KINESIS_ENDPOINT_URL=http://kinesis:4566/
    - AWS_ACCESS_KEY_ID=abc
    - AWS_SECRET_ACCESS_KEY=xyz
    image: ${LOCAL_IMAGE_NAME}
    ports:
    - 8080:8080
    volumes:
    - ./model:/app/model
    - ./scripts:/app/scripts
  kinesis:
    environment:
    - SERVICES=kinesis
    image: localstack/localstack
    ports:
    - 4566:4566
