channels:
- conda-forge
dependencies:
- python=3.9.17
- pip<=23.1.2
- pip:
  - mlflow==2.5.0
  - numpy==1.25.2
  - pandas==2.0.3
  - scikit-learn==1.0.2
  - scipy==1.11.1
  - typing-extensions==4.7.1
  - xgboost==1.7.6
name: mlflow-env
