AWS_REGION="us-east-1"

# Dynamically generated by TF
export MODEL_BUCKET_PROD="prod-mlflow-models-shot-xgoals-mlops-xgoals"
export PREDICTIONS_STREAM_NAME="prod_shot_predictions-mlops-xgoals"
export LAMBDA_FUNCTION="prod_prediction_lambda_mlops-xgoals"

# Model artifacts bucket (MLflow experiments)
export MODEL_BUCKET_DEV="xgoals"

OUTPUT=$(python $PWD/../integration_test/scripts/fetch_run_id.py)
RUN_ID=$(echo "$OUTPUT" | head -n 1)
EXPERIMENT_ID=$(echo "$OUTPUT" | tail -n 1)
echo "Fetched run_id: $RUN_ID"
echo "Fetched experiment_id: $EXPERIMENT_ID"
export RUN_ID
# export RUN_ID=$(aws s3api list-objects-v2 --bucket ${MODEL_BUCKET_DEV} \
# --query 'sort_by(Contents, &LastModified)[-1].Key' --output=text | cut -f2 -d/)

# NOT FOR PRODUCTION!
# Just mocking the artifacts from training process in the Prod env
aws s3 sync s3://${MODEL_BUCKET_DEV} s3://${MODEL_BUCKET_PROD}

# Set new var RUN_ID in existing set of vars.
variables="{PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, MODEL_BUCKET=${MODEL_BUCKET_PROD}, RUN_ID=${RUN_ID}}"

# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION} --environment "Variables=${variables}"
